
GET https://localhost:7053/api/Thought/Recent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1MWViMTNiOC1jZjNjLTQ3ZDEtYWU4My1hZDVmMWUyZTM5ZjgiLCJ1bmlxdWVfbmFtZSI6ImFhbGV4YW5kZXIwNUBnbWFpbC5jb20iLCJleHAiOjE2ODYxNDc2OTYsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwNTMiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDUzIn0.jZV_pAFeKmXwjDVeOFP5YU0mxbxv4n3Hmh2ldu7F_wo
